version: '3.0'

services:
  equipment-api:
      image: equipment-api
      ports:
          - 6001:6001
      environment:      
        - "SPRING_PROFILES_ACTIVE=docker"

  order-api:
      image: order-api
      ports:
          - 6002:6002
      environment:      
        - "SPRING_PROFILES_ACTIVE=docker"

  order-consumer:
      image: order-consumer:0.0.1-SNAPSHOT
      ports:
          - 6003:6003
      environment:      
        - "SPRING_PROFILES_ACTIVE=docker"
        