server:
  port: 9001

app:
  topic: tempTopic

spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=public
    username: postgres
    password: pwd
  flyway:
    enabled: true
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: postgres
    password: pwd
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9200
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer

logging:
  level:
    org.springframework.r2dbc: DEBUG