version: '3.1'

services:
  mongo:
    image: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m -XX:+ExitOnOutOfMemoryError
    ports:
      - 9411:9411


