server:
  port: 8090

spring:
  application:
    name: order-api
  main:
    banner-mode: off
  data:
    mongodb:
      database: dfd
      host: localhost
      port: 27017


springdoc:
  packages-to-scan: com.ere.psc
  paths-to-match: '/v1/**'

apidoc:
  title: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'


# todo kafka
# todo zipkin
# todo mongodb
