server:
  port: 8090

spring:
  application:
    name: order-api
  main:
    banner-mode: off

springdoc:
  packages-to-scan: com.ere.psc
  paths-to-match: '/v1/**'
  api-docs:
    path: /swagger-ui.html

apidoc:
  title: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'